### ISSUE TITLE
Error setPlayer() in the AI Tank

### ISSUE THREAD

**Issue by mfloriani** [mfloriani/tanks#93]
Hey Joe,

AI tank is raising this error:
NullReferenceException: Object reference not set to an instance of an object
TankManager.setPlayer () (at Assets/Joe's Stuff/TankManager.cs:183)
TankManager.Awake () (at Assets/Joe's Stuff/TankManager.cs:322)

It is caused in this line:
![image](https://user-images.githubusercontent.com/13739810/115106509-27984e80-9f5d-11eb-8ec4-f911cf1fd602.png)

Could you help to understand what is the problem or maybe what is the meaning of this line?

**Comment by mfloriani** [comment]
I solved it :)

**Comment by Joe-V2** [comment]
Sorry for the slow reply! What it's trying to do is find a life counter object which is present in the base tank prefab for use with players - if the flag is marked to set it as an ai, it'll destroy it, but in the ai tank prefab the lifecounter doesn't exist, so it can't find it to dispose it.

As a quick fix, a try-catch statement (ideally with a debug.log(errormsg) in the catch) will sort it without causing any issues with using it in the player prefab either
